/*
 * EzOrder Backend
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzOrderBackend);
  }
}(this, function(expect, EzOrderBackend) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Category', function() {
      beforeEach(function() {
        instance = new EzOrderBackend.Category();
      });

      it('should create an instance of Category', function() {
        // TODO: update the code to test Category
        expect(instance).to.be.a(EzOrderBackend.Category);
      });

      it('should have the property catID (base name: "catID")', function() {
        // TODO: update the code to test the property catID
        expect(instance).to.have.property('catID');
        // expect(instance.catID).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property isBookAble (base name: "isBookAble")', function() {
        // TODO: update the code to test the property isBookAble
        expect(instance).to.have.property('isBookAble');
        // expect(instance.isBookAble).to.be(expectedValueLiteral);
      });

      it('should have the property bookableChkText (base name: "bookableChkText")', function() {
        // TODO: update the code to test the property bookableChkText
        expect(instance).to.have.property('bookableChkText');
        // expect(instance.bookableChkText).to.be(expectedValueLiteral);
      });

    });
  });

}));
