/*
 * EzOrder Backend
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzOrderBackend);
  }
}(this, function(expect, EzOrderBackend) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Ordering', function() {
      beforeEach(function() {
        instance = new EzOrderBackend.Ordering();
      });

      it('should create an instance of Ordering', function() {
        // TODO: update the code to test Ordering
        expect(instance).to.be.a(EzOrderBackend.Ordering);
      });

      it('should have the property orderID (base name: "orderID")', function() {
        // TODO: update the code to test the property orderID
        expect(instance).to.have.property('orderID');
        // expect(instance.orderID).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property dateOrder (base name: "dateOrder")', function() {
        // TODO: update the code to test the property dateOrder
        expect(instance).to.have.property('dateOrder');
        // expect(instance.dateOrder).to.be(expectedValueLiteral);
      });

      it('should have the property dateDelivery (base name: "dateDelivery")', function() {
        // TODO: update the code to test the property dateDelivery
        expect(instance).to.have.property('dateDelivery');
        // expect(instance.dateDelivery).to.be(expectedValueLiteral);
      });

      it('should have the property userUserID (base name: "user_userID")', function() {
        // TODO: update the code to test the property userUserID
        expect(instance).to.have.property('userUserID');
        // expect(instance.userUserID).to.be(expectedValueLiteral);
      });

    });
  });

}));
