apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-claim
  namespace: sgse22-tig
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: tig
  volumeMode: Filesystem
  volumeName: grafana-data-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/grafana
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tig
  volumeMode: Filesystem
