apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-claim
  namespace: sgse22-tig
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: tig
  volumeMode: Filesystem
  volumeName: influxdb-data-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/influxdb
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tig
  volumeMode: Filesystem
