/*
 * EzOrder Backend
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzOrderBackend);
  }
}(this, function(expect, EzOrderBackend) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EzOrderBackend.CategoryApi();
  });

  describe('(package)', function() {
    describe('CategoryApi', function() {
      describe('addCategory', function() {
        it('should call addCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for addCategory call
          /*
          var body = new EzOrderBackend.Category();
          body.catID = "0";
          body.name = "";
          body.isBookAble = false;
          body.bookableChkText = "";

          instance.addCategory(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteCategory', function() {
        it('should call deleteCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteCategory call
          /*
          var catID = 789;

          instance.deleteCategory(catID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCategories', function() {
        it('should call getCategories successfully', function(done) {
          // TODO: uncomment getCategories call and complete the assertions
          /*

          instance.getCategories(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EzOrderBackend.Category);
              expect(data.catID).to.be.a('number');
              expect(data.catID).to.be("0");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.isBookAble).to.be.a('boolean');
              expect(data.isBookAble).to.be(false);
              expect(data.bookableChkText).to.be.a('string');
              expect(data.bookableChkText).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCategoryById', function() {
        it('should call getCategoryById successfully', function(done) {
          // TODO: uncomment, update parameter values for getCategoryById call and complete the assertions
          /*
          var catID = 789;

          instance.getCategoryById(catID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EzOrderBackend.Category);
            expect(data.catID).to.be.a('number');
            expect(data.catID).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.isBookAble).to.be.a('boolean');
            expect(data.isBookAble).to.be(false);
            expect(data.bookableChkText).to.be.a('string');
            expect(data.bookableChkText).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateCategory', function() {
        it('should call updateCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for updateCategory call
          /*
          var body = new EzOrderBackend.Category();
          body.catID = "0";
          body.name = "";
          body.isBookAble = false;
          body.bookableChkText = "";

          instance.updateCategory(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateCategoryWithForm', function() {
        it('should call updateCategoryWithForm successfully', function(done) {
          // TODO: uncomment, update parameter values for updateCategoryWithForm call
          /*
          var catID = 789;
          var opts = {};
          opts.name = "name_example";
          opts.status = "status_example";

          instance.updateCategoryWithForm(catID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
