/*
 * EzOrder Backend
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EzOrderBackend);
  }
}(this, function(expect, EzOrderBackend) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EzOrderBackend.OrderingApi();
  });

  describe('(package)', function() {
    describe('OrderingApi', function() {
      describe('deleteOrder', function() {
        it('should call deleteOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteOrder call
          /*
          var orderId = 789;

          instance.deleteOrder(orderId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOrderById', function() {
        it('should call getOrderById successfully', function(done) {
          // TODO: uncomment, update parameter values for getOrderById call and complete the assertions
          /*
          var orderId = 789;

          instance.getOrderById(orderId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EzOrderBackend.Ordering);
            expect(data.orderID).to.be.a('number');
            expect(data.orderID).to.be("0");
            expect(data.status).to.be.a('number');
            expect(data.status).to.be("0");
            expect(data.dateOrder).to.be.a(Date);
            expect(data.dateOrder).to.be(new Date());
            expect(data.dateDelivery).to.be.a(Date);
            expect(data.dateDelivery).to.be(new Date());
            expect(data.userUserID).to.be.a('number');
            expect(data.userUserID).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getOrders', function() {
        it('should call getOrders successfully', function(done) {
          // TODO: uncomment getOrders call and complete the assertions
          /*

          instance.getOrders(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(EzOrderBackend.Ordering);
              expect(data.orderID).to.be.a('number');
              expect(data.orderID).to.be("0");
              expect(data.status).to.be.a('number');
              expect(data.status).to.be("0");
              expect(data.dateOrder).to.be.a(Date);
              expect(data.dateOrder).to.be(new Date());
              expect(data.dateDelivery).to.be.a(Date);
              expect(data.dateDelivery).to.be(new Date());
              expect(data.userUserID).to.be.a('number');
              expect(data.userUserID).to.be("0");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('placeOrder', function() {
        it('should call placeOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for placeOrder call and complete the assertions
          /*
          var body = new EzOrderBackend.Ordering();
          body.orderID = "0";
          body.status = "0";
          body.dateOrder = new Date();
          body.dateDelivery = new Date();
          body.userUserID = "0";

          instance.placeOrder(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EzOrderBackend.Ordering);
            expect(data.orderID).to.be.a('number');
            expect(data.orderID).to.be("0");
            expect(data.status).to.be.a('number');
            expect(data.status).to.be("0");
            expect(data.dateOrder).to.be.a(Date);
            expect(data.dateOrder).to.be(new Date());
            expect(data.dateDelivery).to.be.a(Date);
            expect(data.dateDelivery).to.be(new Date());
            expect(data.userUserID).to.be.a('number');
            expect(data.userUserID).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
