/*
 * EzOrder Backend
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzOrderBackend) {
      root.EzOrderBackend = {};
    }
    root.EzOrderBackend.Ordering = factory(root.EzOrderBackend.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Ordering model module.
   * @module model/Ordering
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Ordering</code>.
   * @alias module:model/Ordering
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Ordering</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ordering} obj Optional instance to populate.
   * @return {module:model/Ordering} The populated <code>Ordering</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('orderID'))
        obj.orderID = ApiClient.convertToType(data['orderID'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
      if (data.hasOwnProperty('dateOrder'))
        obj.dateOrder = ApiClient.convertToType(data['dateOrder'], 'Date');
      if (data.hasOwnProperty('dateDelivery'))
        obj.dateDelivery = ApiClient.convertToType(data['dateDelivery'], 'Date');
      if (data.hasOwnProperty('user_userID'))
        obj.userUserID = ApiClient.convertToType(data['user_userID'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} orderID
   */
  exports.prototype.orderID = undefined;

  /**
   * @member {Number} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {Date} dateOrder
   */
  exports.prototype.dateOrder = undefined;

  /**
   * @member {Date} dateDelivery
   */
  exports.prototype.dateDelivery = undefined;

  /**
   * @member {Number} userUserID
   */
  exports.prototype.userUserID = undefined;


  return exports;

}));
