/*
 * EzOrder Backend
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzOrderBackend) {
      root.EzOrderBackend = {};
    }
    root.EzOrderBackend.Position = factory(root.EzOrderBackend.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Position model module.
   * @module model/Position
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Position</code>.
   * @alias module:model/Position
   * @class
   * @param positionID {Number} 
   */
  var exports = function(positionID) {
    this.positionID = positionID;
  };

  /**
   * Constructs a <code>Position</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Position} obj Optional instance to populate.
   * @return {module:model/Position} The populated <code>Position</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('positionID'))
        obj.positionID = ApiClient.convertToType(data['positionID'], 'Number');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('product_productID'))
        obj.productProductID = ApiClient.convertToType(data['product_productID'], 'Number');
      if (data.hasOwnProperty('ordering_orderID'))
        obj.orderingOrderID = ApiClient.convertToType(data['ordering_orderID'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} positionID
   */
  exports.prototype.positionID = undefined;

  /**
   * @member {Number} amount
   */
  exports.prototype.amount = undefined;

  /**
   * @member {Number} productProductID
   */
  exports.prototype.productProductID = undefined;

  /**
   * @member {Number} orderingOrderID
   */
  exports.prototype.orderingOrderID = undefined;


  return exports;

}));
