/*
 * EzOrder Backend
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.EzOrderBackend) {
      root.EzOrderBackend = {};
    }
    root.EzOrderBackend.Product = factory(root.EzOrderBackend.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Product model module.
   * @module model/Product
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Product</code>.
   * @alias module:model/Product
   * @class
   * @param productID {Number} 
   */
  var exports = function(productID) {
    this.productID = productID;
  };

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Product} obj Optional instance to populate.
   * @return {module:model/Product} The populated <code>Product</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('productID'))
        obj.productID = ApiClient.convertToType(data['productID'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('maxAmount'))
        obj.maxAmount = ApiClient.convertToType(data['maxAmount'], 'Number');
      if (data.hasOwnProperty('packDescription'))
        obj.packDescription = ApiClient.convertToType(data['packDescription'], 'String');
      if (data.hasOwnProperty('category_catID'))
        obj.categoryCatID = ApiClient.convertToType(data['category_catID'], 'Number');
      if (data.hasOwnProperty('imgURL'))
        obj.imgURL = ApiClient.convertToType(data['imgURL'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} productID
   */
  exports.prototype.productID = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Number} maxAmount
   */
  exports.prototype.maxAmount = undefined;

  /**
   * @member {String} packDescription
   */
  exports.prototype.packDescription = undefined;

  /**
   * @member {Number} categoryCatID
   */
  exports.prototype.categoryCatID = undefined;

  /**
   * @member {String} imgURL
   */
  exports.prototype.imgURL = undefined;


  return exports;

}));
