apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shopeconomy-tls-cert
spec:
  secretName: shopeconomy-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "shopeconomy.australiacentral.cloudapp.azure.com"
