apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
        aadpodidbinding: trading # name in Azure ressource group
    spec:
      containers:
        - name: trading
          image: shopeconomy.azurecr.io/trading:1.0.2
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: ServiceSettings__KeyVaultName
              value: shopeconomy
            - name: ServiceSettings__Authority
              value: https://shopeconomy.australiacentral.cloudapp.azure.com/identity-svc
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5006 # same as in Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP
  selector:
    app: trading
  ports:
    - port: 80
      targetPort: 5006 # same as in Dockerfile
