/* 
 * EzOrder Backend
 *
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Category
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CategoryTests
    {
        // TODO uncomment below to declare an instance variable for Category
        //private Category instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Category
            //instance = new Category();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Category
        /// </summary>
        [Test]
        public void CategoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Category
            //Assert.IsInstanceOfType<Category> (instance, "variable 'instance' is a Category");
        }


        /// <summary>
        /// Test the property 'CatID'
        /// </summary>
        [Test]
        public void CatIDTest()
        {
            // TODO unit test for the property 'CatID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IsBookAble'
        /// </summary>
        [Test]
        public void IsBookAbleTest()
        {
            // TODO unit test for the property 'IsBookAble'
        }
        /// <summary>
        /// Test the property 'BookableChkText'
        /// </summary>
        [Test]
        public void BookableChkTextTest()
        {
            // TODO unit test for the property 'BookableChkText'
        }

    }

}
