/* 
 * EzOrder Backend
 *
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Ordering
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderingTests
    {
        // TODO uncomment below to declare an instance variable for Ordering
        //private Ordering instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Ordering
            //instance = new Ordering();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Ordering
        /// </summary>
        [Test]
        public void OrderingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Ordering
            //Assert.IsInstanceOfType<Ordering> (instance, "variable 'instance' is a Ordering");
        }


        /// <summary>
        /// Test the property 'OrderID'
        /// </summary>
        [Test]
        public void OrderIDTest()
        {
            // TODO unit test for the property 'OrderID'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DateOrder'
        /// </summary>
        [Test]
        public void DateOrderTest()
        {
            // TODO unit test for the property 'DateOrder'
        }
        /// <summary>
        /// Test the property 'DateDelivery'
        /// </summary>
        [Test]
        public void DateDeliveryTest()
        {
            // TODO unit test for the property 'DateDelivery'
        }
        /// <summary>
        /// Test the property 'UserUserID'
        /// </summary>
        [Test]
        public void UserUserIDTest()
        {
            // TODO unit test for the property 'UserUserID'
        }

    }

}
