/* 
 * EzOrder Backend
 *
 * API Description for EzOrder Rest-Backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Position
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PositionTests
    {
        // TODO uncomment below to declare an instance variable for Position
        //private Position instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Position
            //instance = new Position();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Position
        /// </summary>
        [Test]
        public void PositionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Position
            //Assert.IsInstanceOfType<Position> (instance, "variable 'instance' is a Position");
        }


        /// <summary>
        /// Test the property 'PositionID'
        /// </summary>
        [Test]
        public void PositionIDTest()
        {
            // TODO unit test for the property 'PositionID'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'ProductProductID'
        /// </summary>
        [Test]
        public void ProductProductIDTest()
        {
            // TODO unit test for the property 'ProductProductID'
        }
        /// <summary>
        /// Test the property 'OrderingOrderID'
        /// </summary>
        [Test]
        public void OrderingOrderIDTest()
        {
            // TODO unit test for the property 'OrderingOrderID'
        }

    }

}
