apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sgse22-harbor
  namespace: flux
spec:
  interval: 30s
  path: ./deployment/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: sgse22
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
spec:
  url: https://helm.goharbor.io
  interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30s
  chart:
    spec:
      chart: harbor
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
  valuesFrom:
    - kind: ConfigMap
      name: harbor-values
      valuesKey: values.yml
