apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: sgse22
  namespace: flux
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://git-url/kubernetes_deployment.git
