apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sgse22-tig
  namespace: flux
spec:
  interval: 30s
  path: ./deployment/tig-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: sgse22
