apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sgse22
  namespace: flux
spec:
  interval: 30s
  path: ./deployment/webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: sgse22
